######################################################################
# Automatically generated by qmake (2.00a) Sat Apr 1 14:55:23 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += . src
INCLUDEPATH += . src

include(INSERT_YUOR_PATH_HERE_TO_THE_PROPERTY_BROWSER_SOLUTION/src/qtpropertybrowser.pri)
# Input
SOURCES += main.cpp
