######################################################################
# Automatically generated by qmake (2.00a) Sat Apr 1 14:55:23 2006
######################################################################

TEMPLATE = app
TARGET += 
DEPENDPATH += . src
INCLUDEPATH += . src

include(../qtpropertybrowser/qtpropertybrowser.pri)
# Input
SOURCES += main.cpp
